### ISSUE TITLE
Alignment options from Gutenberg and "Additional CSS classes" are ignored

### ISSUE THREAD

**Issue by MShekow** [futtta/wp-youtube-lyte#16]
When embedding a YT video with Gutenberg, and having this plug-in enabled, the video is always only aligned according to the plugin settings, which is very limiting.
It would be nice if the plug-in applied the alignment-values from the Gutenberg block, and also to actually forward additional CSS classes set for the Gutenberg block to the HTML renderer. This would allow me to let text flow around videos (which already works for normal images).
Thank you.

**Comment by futtta** [comment]
Consider it added to the backlog this way @MShekow , but not sure when I'll be able to work on this. Feel free to contribute (fork & change & issue a pull request) if you have time :)

**Comment by benjaminpick** [comment]
Hi, I started working on this. However I can't figure out how to write the regex to capture the align property. I tried: `<\!--\s?wp:(?:core[-|/])?embed(?:/youtube)?\s?{"url":"https://www.youtube.com/playlist\?list=(.*)"(?:.*)?(?:"align":"([a-z]*)")?(?:.*)?}\s?-->.*(?:(?:<figcaption[^>]*></figcaption>*>(.*)</figcaption>).*)?<\!--\s?/wp:(?:core[-|/])?embed(?:/youtube)?\s?-->` - however, this never captures the align value except when I make the align property mandatory (but I can't, because not all Youtube block have this property.) The same problem, btw, seems to exist currenlty for the figcaption capture group - it also doesn't find the value.

Possible ways forward:

- Give up the regex and use Gutenberg's function `parse_blocks` instead (are you using regex for performance reasons?)
- Use preg_replace_callback in order to parse the block arguments with json_decode

For performance, we could do this parsing on save instead of during the rendering of the page?

**Comment by futtta** [comment]
hmm, can you paste an example blob of the Gutenberg youtube HTML with an align attribute, I'll take a look at it ;-)

**Comment by benjaminpick** [comment]
Sure thing! Here is the blob as generated by Wordpress 6.2 :

```html

<!-- wp:embed {"url":"https://www.youtube.com/playlist?list=PLwjoqDa8kUBJQ-t3PTCzopM0rRNRo_gUe","type":"video","providerNameSlug":"youtube","responsive":true,"align":"full","className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed alignfull is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://www.youtube.com/playlist?list=PLwjoqDa8kUBJQ-t3PTCzopM0rRNRo_gUe
</div><figcaption class="wp-element-caption">Caption</figcaption></figure>
<!-- /wp:embed -->
```

The possible values for align are: `wide`, `full`, `left`, `center`, `right`  and unset (no align property in the json array) .

**Comment by futtta** [comment]
been playing around with the regex on https://regex101.com/r/6BccX7/1 but can't get it to work either; as soon as the align property/ value is optional, it isn't caught any more ... :-/

**Comment by benjaminpick** [comment]
:-( How about I capture the json as a whole, then parse it with json_decode, and I do some performance testing to see how much difference this makes. Because as it simplifies the regex, the regex should maybe be faster to execute ....
https://regex101.com/r/8ijNot/1

**Comment by futtta** [comment]
I would indeed try to emulate?

**Comment by benjaminpick** [comment]
Here is a snippet to disable gutenbeard temporarily for testing:
```add_filter('lyte_filter_do_gutenberg', function() {
    if (!empty($_GET['disable_gutenbeard'])) return false;
});
```

**Comment by benjaminpick** [comment]
CSS:
Comparing the different Wordpress theme, I think we should treat the way how the alignment CSS classes are interpreted as theme territorry. In the current pull request it uses the wordpress classes and adds some classes to make our lyte wrapper behave similarly to the Wordpress embeds. Would there be a possibility to call for beta testers if this works in their theme? 

I don't think we have to treat this as backwards compatibility break as "align none" is the default option and if they selected e.g. "align center" it's because they want it centered.

Performance: 
Quick test with my test page containing 4 playlists & 1 video
previously: around 0.02ms for the gutenbeard section,
now: around 0.05ms

**Comment by benjaminpick** [comment]
From my side, the pull request works well. Is there something you think needs to be done before this can be merged?
