### ISSUE TITLE
Add option to disable lazyload for content above the fold

### ISSUE THREAD

**Issue by danielbald** [futtta/wp-youtube-lyte#41]
Can you add a feature to selectively, ie a shortcode option, to disable lazy load?

This is to keep PageSpeed happy as it will reduce LCP.

**Comment by futtta** [comment]
When on mobile by default LYTE's are replaced with the real YTembed soon,
so that means that the LCP is the YT video itself. ticking the "cache
thumbnails locally" will change LYTE's behavior for mobile into the one for
desktop; not loading the YT vid until being clicked on so that would help
LCP.

For the images in a LYTE vid (placeholder) are loaded as background image,
so they always indeed load with somewhat lower priority. disabling LYTE as
a whole for above the fold videos would have an even bigger impact on LCP
(as described in previous paragraph), so not sure if there's a (somewhat
simple) solution for that.

**Comment by danielbald** [comment]
Thank you very much for such a fast response. That makes sense. I've enabled local cache.
